[ids]

# My wired keyboard
05af:0802:20f521c9
# My wireless keyboard
248a:8367:d68bf1db

# My mouse
09da:9090:0ae1f585
# Mouse virtual keyboard
09da:9090:323ae3f1


[main]

# Fix for some weird issue
rightshift = rightshift
rightcontrol = rightcontrol
rightmeta = rightmeta

# Key remapping
insert = delete
scrolllock = insert

# Double-purpose key
rightalt = overloadt(altgr, 102nd, 200)

# Mouse mod
mouse2 = layer(mousemod)


[mousemod]

leftmouse = C-a
rightmouse = A-f4
middlemouse = C-x
scrolldown = swapm(wheelblock, C-c)
scrollup = swapm(wheelblock, C-v)
delete = backspace


[wheelblock]

scrolldown = noop
scrollup = noop
