[ids]

# My keyboard
248a:8367:d68bf1db

[main]

# Fix for some weird issue
rightshift = rightshift
rightcontrol = rightcontrol
rightmeta = rightmeta

# Key remapping
insert = delete
scrolllock = insert

# Double-purpose key
rightalt = overloadt(altgr, 102nd, 250)
